apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-pipeline
spec:
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: 'https://github.com/rohit-taneja-redhat/tekton-is-groovy-pipeline'
        - name: revision
          value: main
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: build-and-push
      params:
        - name: MAVEN_IMAGE
          value: registry.access.redhat.com/ubi8/openjdk-11
        - name: CONTEXT_DIR
          value: .
        - name: GOALS
          value:
            - '-DskipTests'
            - package
            - '-Dquarkus.container-image.build=true'
	    - '-Dquarkus.container-image.push=true'
            - '-Dquarkus.container-image.group=tekton-is-groovy'
            - '-Dquarkus.container-image.registry=image-registry.openshift-image-registry.svc:5000'
            - '-Dquarkus.container-image.name=tekton-is-groovy'
            - '-Dquarkus.container-image.insecure=true'
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: maven-settings
          workspace: maven-settings
        - name: source
          workspace: shared-workspace
  workspaces:
    - name: maven-settings
    - name: shared-workspace

